# Generated by Django 3.2 on 2021-05-02 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_dog_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
    ]
